/*
 * PreferenceWindow.java
 *
 * Created on __DATE__, __TIME__
 */

package com.funnyChat.core;

import java.util.Collection;
import java.util.Iterator;

import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;

import com.funnyChat.plugin.*;

/**
 *
 * @author  __USER__
 */
public class PreferenceWindow extends javax.swing.JDialog {

	/** Creates new form PreferenceWindow */
	public PreferenceWindow(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		initializePM();
		this.setLocation(200, 200);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTabbedPane1.setToolTipText("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 395,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 469,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("Plugin Management", jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void initializePM() {
		Collection<Plugin> _plugins = PluginManager.getInstance().getPlugins();
		Iterator<Plugin> _iter = _plugins.iterator();
		mPluginCBs = new javax.swing.JCheckBox[_plugins.size()];
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(layout);
		ParallelGroup _pgh = layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING);
		SequentialGroup _pgv = layout.createSequentialGroup().addContainerGap();

		for (int i = 0; i < _plugins.size(); i++) {
			mPluginCBs[i] = new javax.swing.JCheckBox();
			Plugin _plugin = _iter.next();
			String _name = _plugin.getPluginName();
			mPluginCBs[i].setText(_name);
			mPluginCBs[i].setSelected(_plugin.isEnabled());

			_pgh.addComponent(mPluginCBs[i]);
			
			if(i < _plugins.size() - 1) {
				_pgv.addComponent(mPluginCBs[i]).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED);
			}
			else {
				_pgv.addComponent(mPluginCBs[i]).addContainerGap(259, Short.MAX_VALUE);
			}
		}
		
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(_pgh)
								.addContainerGap(329, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(_pgv));
	}

	/**
	 * @param args the command line arguments
	 */
	/*public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PreferenceWindow dialog = new PreferenceWindow(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}*/

	private javax.swing.JCheckBox[] mPluginCBs;
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}