/*
 * PreferenceWindow.java
 *
 * Created on __DATE__, __TIME__
 */

package com.funnyChat.core;

import java.util.Collection;
import java.util.Vector;

import com.funnyChat.plugin.Plugin;
import com.funnyChat.plugin.PluginManager;

/**
 * 
 * @author __USER__
 */
public class PreferenceWindow extends javax.swing.JDialog {

	/** Creates new form PreferenceWindow */
	public PreferenceWindow(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		initializePM();
		this.setLocation(200, 200);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		JBT_move_enable = new javax.swing.JButton();
		JBT_move_disable = new javax.swing.JButton();
		JLB_disable = new javax.swing.JLabel();
		JLB_enable = new javax.swing.JLabel();
		JBT_ok = new javax.swing.JButton();
		JBT_cancel = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		JL_disable = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		JL_enable = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTabbedPane1.setToolTipText("");

		JBT_move_enable.setText(">>");
		JBT_move_enable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				JBT_move_enableMouseClicked(evt);
			}
		});

		JBT_move_disable.setText("<<");
		JBT_move_disable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				JBT_move_disableMouseClicked(evt);
			}
		});

		JLB_disable.setText("Disable");

		JLB_enable.setText("Enable");

		JBT_ok.setText("OK");
		JBT_ok.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				JBT_okMouseClicked(evt);
			}
		});

		JBT_cancel.setText("CANCEL");
		JBT_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				JBT_cancelMouseClicked(evt);
			}
		});

		JL_disable.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(JL_disable);

		JL_enable.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(JL_enable);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												148,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																JBT_move_enable,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																69,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																JBT_move_disable,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																69,
																																Short.MAX_VALUE)))
																						.addComponent(
																								JLB_disable))
																		.addGap(
																				12,
																				12,
																				12)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								156,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								JLB_enable))
																		.addGap(
																				12,
																				12,
																				12))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				JBT_ok,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				72,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				JBT_cancel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				92,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				61,
																				61,
																				61)
																		.addComponent(
																				JBT_move_enable,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				JBT_move_disable,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								JLB_disable)
																						.addComponent(
																								JLB_enable))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								326,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								326,
																								Short.MAX_VALUE))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																JBT_ok,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																42,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																JBT_cancel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																40,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)));

		jTabbedPane1.addTab("Plugin Management", jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jTabbedPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 452,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void JBT_cancelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void JBT_okMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		updatePluginState();
		this.dispose();
	}

	private void JBT_move_disableMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if (JL_enable.getSelectedIndex() != -1) {
			Vector<String> _enable_list = new Vector<String>();
			Vector<String> _disable_list = new Vector<String>();

			for (int i = 0; i != JL_disable.getModel().getSize(); ++i) {
				_disable_list.add(String.valueOf(JL_disable.getModel()
						.getElementAt(i)));
			}
			for (int i = 0; i != JL_enable.getModel().getSize(); ++i) {
				if (JL_enable.isSelectedIndex(i)) {
					_disable_list.add(String.valueOf(JL_enable.getModel()
							.getElementAt(i)));
				} else {
					_enable_list.add(String.valueOf(JL_enable.getModel()
							.getElementAt(i)));
				}
			}
			JL_enable.setListData(_enable_list);
			JL_disable.setListData(_disable_list);
			mEnableList = _enable_list;
			mDisableList = _disable_list;
		}
	}

	private void JBT_move_enableMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if (JL_disable.getSelectedIndex() != -1) {
			Vector<String> _enable_list = new Vector<String>();
			Vector<String> _disable_list = new Vector<String>();

			for (int i = 0; i != JL_enable.getModel().getSize(); ++i) {
				_enable_list.add(String.valueOf(JL_enable.getModel()
						.getElementAt(i)));
			}
			for (int i = 0; i != JL_disable.getModel().getSize(); ++i) {
				if (JL_disable.isSelectedIndex(i)) {
					_enable_list.add(String.valueOf(JL_disable.getModel()
							.getElementAt(i)));
				} else {
					_disable_list.add(String.valueOf(JL_disable.getModel()
							.getElementAt(i)));
				}
			}
			JL_enable.setListData(_enable_list);
			JL_disable.setListData(_disable_list);
			mEnableList = _enable_list;
			mDisableList = _disable_list;
		}
	}

	private void initializePM() {
		Collection<Plugin> _plugins = PluginManager.getInstance().getPlugins();

		mEnableList = new Vector<String>();
		mDisableList = new Vector<String>();

		for (Plugin _plugin : _plugins) {
			if (_plugin.isEnabled())
				mEnableList.add(_plugin.getPluginName());
			else
				mDisableList.add(_plugin.getPluginName());
		}
		JL_enable.setListData(mEnableList);
		JL_disable.setListData(mDisableList);
	}

	private void updatePluginState() {
		Collection<Plugin> _plugins = PluginManager.getInstance().getPlugins();
		for (Plugin _plugin : _plugins) {
			if (mEnableList.contains(_plugin.getPluginName()))
				_plugin.enable();
			else
				_plugin.disable();
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PreferenceWindow dialog = new PreferenceWindow(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						e.getWindow().dispose();
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// private javax.swing.JCheckBox[] mPluginCBs;
	private Vector<String> mEnableList;
	private Vector<String> mDisableList;

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton JBT_cancel;
	private javax.swing.JButton JBT_move_disable;
	private javax.swing.JButton JBT_move_enable;
	private javax.swing.JButton JBT_ok;
	private javax.swing.JLabel JLB_disable;
	private javax.swing.JLabel JLB_enable;
	private javax.swing.JList JL_disable;
	private javax.swing.JList JL_enable;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}